
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/DutchPayIt
    driver-class-name: org.h2.Driver
    username: c_team
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true