spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dutchpay-it-rdb.cicoecqa7q2u.ap-northeast-2.rds.amazonaws.com:3306/dutchpay_it_db
    username: admin
    password: 'sean9045'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug